/* File: fpostprocmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Wed Apr 12 16:03:21 2017
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *fpostproc_error;
static PyObject *fpostproc_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
  if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
    PyErr_SetString(PyExc_MemoryError, "out of memory");\
    goto capi_fail;\
  } else {\
    (str)[len] = '\0';\
  }

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(fpostproc_error,errstring);\
    /*goto capi_fail;*/\
  } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = fpostproc_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
  if (obj == Py_None) {
    if (*len == -1)
      *len = strlen(inistr); /* Will this cause problems? */
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,inistr,*len+1);
    return 1;
  }
  if (PyArray_Check(obj)) {
    if ((arr = (PyArrayObject *)obj) == NULL)
      goto capi_fail;
    if (!ISCONTIGUOUS(arr)) {
      PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
      goto capi_fail;
    }
    if (*len == -1)
      *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
    return 1;
  }
  if (PyString_Check(obj)) {
    tmp = obj;
    Py_INCREF(tmp);
  }
#if PY_VERSION_HEX >= 0x03000000
  else if (PyUnicode_Check(obj)) {
    tmp = PyUnicode_AsASCIIString(obj);
  }
  else {
    PyObject *tmp2;
    tmp2 = PyObject_Str(obj);
    if (tmp2) {
      tmp = PyUnicode_AsASCIIString(tmp2);
      Py_DECREF(tmp2);
    }
    else {
      tmp = NULL;
    }
  }
#else
  else {
    tmp = PyObject_Str(obj);
  }
#endif
  if (tmp == NULL) goto capi_fail;
  if (*len == -1)
    *len = PyString_GET_SIZE(tmp);
  STRINGMALLOC(*str,*len);
  STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
  Py_DECREF(tmp);
  return 1;
capi_fail:
  Py_XDECREF(tmp);
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = fpostproc_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = fpostproc_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(POSTPROC,POSTPROC)(string,int*,double*,double*,double*,int*,int*,int*,double*,double*,size_t);
extern void F_FUNC_US(AVG_T,AVG_T)(int*,int*,double*,int*,int*,string,double*,double*,size_t);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** POSTPROC **********************************/
static char doc_f2py_rout_fpostproc_POSTPROC[] = "\
POSTPROC(dir,z_scale,u_star,dt_dim,nt,tini,tend,T_scale,outdata,[nz])\n\nWrapper for ``POSTPROC``.\
\n\nParameters\n----------\n"
"dir : input string(len=100)\n"
"z_scale : input float\n"
"u_star : input float\n"
"dt_dim : input float\n"
"nt : input int\n"
"tini : input int\n"
"tend : input int\n"
"T_scale : input float\n"
"outdata : input rank-2 array('d') with bounds (23,nz)\n"
"\nOther Parameters\n----------------\n"
"nz : input int, optional\n    Default: shape(outdata,1)";
/* extern void F_FUNC(POSTPROC,POSTPROC)(string,int*,double*,double*,double*,int*,int*,int*,double*,double*,size_t); */
static PyObject *f2py_rout_fpostproc_POSTPROC(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,int*,double*,double*,double*,int*,int*,int*,double*,double*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string dir = NULL;
  int slen(dir);
  PyObject *dir_capi = Py_None;
  int nz = 0;
  PyObject *nz_capi = Py_None;
  double z_scale = 0;
  PyObject *z_scale_capi = Py_None;
  double u_star = 0;
  PyObject *u_star_capi = Py_None;
  double dt_dim = 0;
  PyObject *dt_dim_capi = Py_None;
  int nt = 0;
  PyObject *nt_capi = Py_None;
  int tini = 0;
  PyObject *tini_capi = Py_None;
  int tend = 0;
  PyObject *tend_capi = Py_None;
  double T_scale = 0;
  PyObject *T_scale_capi = Py_None;
  double *outdata = NULL;
  npy_intp outdata_Dims[2] = {-1, -1};
  const int outdata_Rank = 2;
  PyArrayObject *capi_outdata_tmp = NULL;
  int capi_outdata_intent = 0;
  PyObject *outdata_capi = Py_None;
  static char *capi_kwlist[] = {"dir","z_scale","u_star","dt_dim","nt","tini","tend","T_scale","outdata","nz",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO|O:fpostproc.POSTPROC",\
    capi_kwlist,&dir_capi,&z_scale_capi,&u_star_capi,&dt_dim_capi,&nt_capi,&tini_capi,&tend_capi,&T_scale_capi,&outdata_capi,&nz_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable u_star */
    f2py_success = double_from_pyobj(&u_star,u_star_capi,"fpostproc.POSTPROC() 3rd argument (u_star) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dir */
  slen(dir) = 100;
  f2py_success = string_from_pyobj(&dir,&slen(dir),"",dir_capi,"string_from_pyobj failed in converting 1st argument `dir' of fpostproc.POSTPROC to C string");
  if (f2py_success) {
  /* Processing variable z_scale */
    f2py_success = double_from_pyobj(&z_scale,z_scale_capi,"fpostproc.POSTPROC() 2nd argument (z_scale) can't be converted to double");
  if (f2py_success) {
  /* Processing variable tend */
    f2py_success = int_from_pyobj(&tend,tend_capi,"fpostproc.POSTPROC() 7th argument (tend) can't be converted to int");
  if (f2py_success) {
  /* Processing variable outdata */
  outdata_Dims[0]=23;
  capi_outdata_intent |= F2PY_INTENT_IN;
  capi_outdata_tmp = array_from_pyobj(NPY_DOUBLE,outdata_Dims,outdata_Rank,capi_outdata_intent,outdata_capi);
  if (capi_outdata_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fpostproc_error,"failed in converting 9th argument `outdata' of fpostproc.POSTPROC to C/Fortran array" );
  } else {
    outdata = (double *)(PyArray_DATA(capi_outdata_tmp));

  /* Processing variable dt_dim */
    f2py_success = double_from_pyobj(&dt_dim,dt_dim_capi,"fpostproc.POSTPROC() 4th argument (dt_dim) can't be converted to double");
  if (f2py_success) {
  /* Processing variable T_scale */
    f2py_success = double_from_pyobj(&T_scale,T_scale_capi,"fpostproc.POSTPROC() 8th argument (T_scale) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nt */
    f2py_success = int_from_pyobj(&nt,nt_capi,"fpostproc.POSTPROC() 5th argument (nt) can't be converted to int");
  if (f2py_success) {
  /* Processing variable tini */
    f2py_success = int_from_pyobj(&tini,tini_capi,"fpostproc.POSTPROC() 6th argument (tini) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nz */
  if (nz_capi == Py_None) nz = shape(outdata,1); else
    f2py_success = int_from_pyobj(&nz,nz_capi,"fpostproc.POSTPROC() 1st keyword (nz) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(outdata,1)==nz,"shape(outdata,1)==nz","1st keyword nz","POSTPROC:nz=%d",nz) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(dir,&nz,&z_scale,&u_star,&dt_dim,&nt,&tini,&tend,&T_scale,outdata,slen(dir));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(outdata,1)==nz)*/
  } /*if (f2py_success) of nz*/
  /* End of cleaning variable nz */
  } /*if (f2py_success) of tini*/
  /* End of cleaning variable tini */
  } /*if (f2py_success) of nt*/
  /* End of cleaning variable nt */
  } /*if (f2py_success) of T_scale*/
  /* End of cleaning variable T_scale */
  } /*if (f2py_success) of dt_dim*/
  /* End of cleaning variable dt_dim */
  if((PyObject *)capi_outdata_tmp!=outdata_capi) {
    Py_XDECREF(capi_outdata_tmp); }
  }  /*if (capi_outdata_tmp == NULL) ... else of outdata*/
  /* End of cleaning variable outdata */
  } /*if (f2py_success) of tend*/
  /* End of cleaning variable tend */
  } /*if (f2py_success) of z_scale*/
  /* End of cleaning variable z_scale */
    STRINGFREE(dir);
  }  /*if (f2py_success) of dir*/
  /* End of cleaning variable dir */
  } /*if (f2py_success) of u_star*/
  /* End of cleaning variable u_star */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of POSTPROC ******************************/

/*********************************** AVG_T ***********************************/
static char doc_f2py_rout_fpostproc_AVG_T[] = "\
AVG_T(dt,tini,tend,file,scale_factor,avg,[nz,nt])\n\nWrapper for ``AVG_T``.\
\n\nParameters\n----------\n"
"dt : input float\n"
"tini : input int\n"
"tend : input int\n"
"file : input string(len=-1)\n"
"scale_factor : input rank-1 array('d') with bounds (nt)\n"
"avg : input rank-1 array('d') with bounds (nz)\n"
"\nOther Parameters\n----------------\n"
"nz : input int, optional\n    Default: len(avg)\n"
"nt : input int, optional\n    Default: len(scale_factor)";
/* extern void F_FUNC_US(AVG_T,AVG_T)(int*,int*,double*,int*,int*,string,double*,double*,size_t); */
static PyObject *f2py_rout_fpostproc_AVG_T(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,int*,int*,string,double*,double*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int nz = 0;
  PyObject *nz_capi = Py_None;
  int nt = 0;
  PyObject *nt_capi = Py_None;
  double dt = 0;
  PyObject *dt_capi = Py_None;
  int tini = 0;
  PyObject *tini_capi = Py_None;
  int tend = 0;
  PyObject *tend_capi = Py_None;
  string file = NULL;
  int slen(file);
  PyObject *file_capi = Py_None;
  double *scale_factor = NULL;
  npy_intp scale_factor_Dims[1] = {-1};
  const int scale_factor_Rank = 1;
  PyArrayObject *capi_scale_factor_tmp = NULL;
  int capi_scale_factor_intent = 0;
  PyObject *scale_factor_capi = Py_None;
  double *avg = NULL;
  npy_intp avg_Dims[1] = {-1};
  const int avg_Rank = 1;
  PyArrayObject *capi_avg_tmp = NULL;
  int capi_avg_intent = 0;
  PyObject *avg_capi = Py_None;
  static char *capi_kwlist[] = {"dt","tini","tend","file","scale_factor","avg","nz","nt",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|OO:fpostproc.AVG_T",\
    capi_kwlist,&dt_capi,&tini_capi,&tend_capi,&file_capi,&scale_factor_capi,&avg_capi,&nz_capi,&nt_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable scale_factor */
  ;
  capi_scale_factor_intent |= F2PY_INTENT_IN;
  capi_scale_factor_tmp = array_from_pyobj(NPY_DOUBLE,scale_factor_Dims,scale_factor_Rank,capi_scale_factor_intent,scale_factor_capi);
  if (capi_scale_factor_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fpostproc_error,"failed in converting 5th argument `scale_factor' of fpostproc.AVG_T to C/Fortran array" );
  } else {
    scale_factor = (double *)(PyArray_DATA(capi_scale_factor_tmp));

  /* Processing variable tend */
    f2py_success = int_from_pyobj(&tend,tend_capi,"fpostproc.AVG_T() 3rd argument (tend) can't be converted to int");
  if (f2py_success) {
  /* Processing variable file */
  slen(file) = -1;
  f2py_success = string_from_pyobj(&file,&slen(file),"",file_capi,"string_from_pyobj failed in converting 4th argument `file' of fpostproc.AVG_T to C string");
  if (f2py_success) {
  /* Processing variable dt */
    f2py_success = double_from_pyobj(&dt,dt_capi,"fpostproc.AVG_T() 1st argument (dt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable avg */
  ;
  capi_avg_intent |= F2PY_INTENT_IN;
  capi_avg_tmp = array_from_pyobj(NPY_DOUBLE,avg_Dims,avg_Rank,capi_avg_intent,avg_capi);
  if (capi_avg_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fpostproc_error,"failed in converting 6th argument `avg' of fpostproc.AVG_T to C/Fortran array" );
  } else {
    avg = (double *)(PyArray_DATA(capi_avg_tmp));

  /* Processing variable tini */
    f2py_success = int_from_pyobj(&tini,tini_capi,"fpostproc.AVG_T() 2nd argument (tini) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nz */
  if (nz_capi == Py_None) nz = len(avg); else
    f2py_success = int_from_pyobj(&nz,nz_capi,"fpostproc.AVG_T() 1st keyword (nz) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(avg)>=nz,"len(avg)>=nz","1st keyword nz","AVG_T:nz=%d",nz) {
  /* Processing variable nt */
  if (nt_capi == Py_None) nt = len(scale_factor); else
    f2py_success = int_from_pyobj(&nt,nt_capi,"fpostproc.AVG_T() 2nd keyword (nt) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(scale_factor)>=nt,"len(scale_factor)>=nt","2nd keyword nt","AVG_T:nt=%d",nt) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&nz,&nt,&dt,&tini,&tend,file,scale_factor,avg,slen(file));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(scale_factor)>=nt)*/
  } /*if (f2py_success) of nt*/
  /* End of cleaning variable nt */
  } /*CHECKSCALAR(len(avg)>=nz)*/
  } /*if (f2py_success) of nz*/
  /* End of cleaning variable nz */
  } /*if (f2py_success) of tini*/
  /* End of cleaning variable tini */
  if((PyObject *)capi_avg_tmp!=avg_capi) {
    Py_XDECREF(capi_avg_tmp); }
  }  /*if (capi_avg_tmp == NULL) ... else of avg*/
  /* End of cleaning variable avg */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
    STRINGFREE(file);
  }  /*if (f2py_success) of file*/
  /* End of cleaning variable file */
  } /*if (f2py_success) of tend*/
  /* End of cleaning variable tend */
  if((PyObject *)capi_scale_factor_tmp!=scale_factor_capi) {
    Py_XDECREF(capi_scale_factor_tmp); }
  }  /*if (capi_scale_factor_tmp == NULL) ... else of scale_factor*/
  /* End of cleaning variable scale_factor */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of AVG_T ********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"POSTPROC",-1,{{-1}},0,(char *)F_FUNC(POSTPROC,POSTPROC),(f2py_init_func)f2py_rout_fpostproc_POSTPROC,doc_f2py_rout_fpostproc_POSTPROC},
  {"AVG_T",-1,{{-1}},0,(char *)F_FUNC_US(AVG_T,AVG_T),(f2py_init_func)f2py_rout_fpostproc_AVG_T,doc_f2py_rout_fpostproc_AVG_T},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "fpostproc",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_fpostproc(void) {
#else
#define RETVAL
PyMODINIT_FUNC initfpostproc(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = fpostproc_module = PyModule_Create(&moduledef);
#else
  m = fpostproc_module = Py_InitModule("fpostproc", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module fpostproc (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'fpostproc' is auto-generated with f2py (version:2).\nFunctions:\n"
"  POSTPROC(dir,z_scale,u_star,dt_dim,nt,tini,tend,T_scale,outdata,nz=shape(outdata,1))\n"
"  AVG_T(dt,tini,tend,file,scale_factor,avg,nz=len(avg),nt=len(scale_factor))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  fpostproc_error = PyErr_NewException ("fpostproc.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));


/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"fpostproc");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
